name = "Kraken"
version = "0.1.0"
defaultTargets = ["Kraken", "krakenrunner", "att2intel"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "KrakenTactics"
precompileModules = true
globs = ["KrakenTactics.*"]

[[lean_lib]]
name = "BenchLib"
precompileModules = true
srcDir = "bench/lib"
globs = ["Driver"]

[[lean_lib]]
name = "Cases"
srcDir = "bench"
globs = ["Cases", "Cases.*"]

[[lean_lib]]
name = "Kraken"
globs = ["Kraken.*"]  # TODO: move the tests out of `Kraken`

[[lean_exe]]
name = "krakenrunner"
root = "KrakenRunner"

[[lean_exe]]
name = "att2intel"
root = "Att2Intel"
